apiVersion: v2
name: mongodb
version: 0.2.0
appVersion: "7.0.0"
description: A Helm chart deploying a three-member MongoDB replica set
keywords:
  - mongodb
  - database
  - replicaset
home: https://www.mongodb.com/
icon: https://www.mongodb.com/assets/images/global/favicon.ico
sources:
  - https://www.mongodb.com/docs/
dependencies: []
type: application
