{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb.fullname" . }}-auth
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
  replicaSetKey: {{ .Values.auth.replicaSetKey | b64enc | quote }}
{{- end }}
